### ISSUE TITLE
Comcast Local Domains

### ISSUE THREAD

**Issue by QuantumWarpCode** [gwarser/filter-lists#11]
It has come to my attention that new Comcast routers define an extra set of domains for local ips. They all look like the following.

`*.hsd1.*.comcast.net`

Perhaps a filter like this should be added? (I think the asterisk is improper syntax but it'd be something similar.

`||hsd1.*.comcast.net^$third-party,domain=~localhost|~[::1]|~127.0.0.1|~0.0.0.0|~[::]`

**Comment by gwarser** [comment]
Do you have any source? These looks like some internal Comcast severs, see here https://forums.businesshelp.comcast.com/conversations/domain-namesstatic-ip/bad-routes-to-static-ips-in-comcast-router-c501339064hsd1micomcastnet/5fe0a5cdc5375f08cd882ce6 

Local router seem to be `router.asus.com`.

**Comment by QuantumWarpCode** [comment]
My source is my own logs, but it appears from your post this might not something to block. If I had a computer on my network named PCName, I would see DNS requests sent to my router for PCName.hsd1.co.comcast.net that return the correct local ip for the device. If there are Comcast servers that use the same format however, then blocking this might break things.
