### ISSUE TITLE
Add fritz.repeater and myfritz.box to lan-block.txt

### ISSUE THREAD

**Issue by PaulEwe** [gwarser/filter-lists#12]
[source](https://en.avm.de/service/fritzwlan/fritzrepeater-3000/knowledge-base/publication/show/412_Opening-the-user-interface-of-FRITZ-Repeater/)

**Comment by gwarser** [comment]
https://github.com/gwarser/filter-lists/commit/ee6d7a3a72f4e5e552ee695370739790f52a7abe

Thanks.

**Comment by PaulEwe** [comment]
Sorry to bother again, but the Fritz!Box is also accessable from `myfritz.box`. 
[source](https://service.avm.de/help/en/FRITZ-Box-7430/018/hilfe_was_ist_myfritz) (section MyFRITZ! in the Home Network)

But that should be it now, according to the self-signed ssl certificate.
![grafik](https://user-images.githubusercontent.com/29153708/106835375-8c027c00-6697-11eb-94f5-c9a31b47da22.png)

**Comment by gwarser** [comment]
Thanks!

https://github.com/gwarser/filter-lists/commit/d428052fc99fc6ca28b736e6373ddaa7972fa2e7
