### ISSUE TITLE
Pi-hole

### ISSUE THREAD

**Issue by PasswordIs0000** [gwarser/filter-lists#13]
Hey! Just realized that your local LAN blocker list is now in uBlock Origin. Nice idea to make such a list, thanks for that!

A suggestion: Can you please add the Pi-hole DNS server? Homepage of the software is https://pi-hole.net/ and in the local LAN it is reachable as http://pi.hole

I think blocking this in addition to routers would be nice.

**Comment by gwarser** [comment]
Thanks.
