### ISSUE TITLE
Intel Drivers and Support Assistant uses LAN

### ISSUE THREAD

**Issue by Jap2-0** [gwarser/filter-lists#19]
Lan-block breaks the Intel Driver and Support Assistant (https://www.intel.com/content/www/us/en/support/intel-driver-support-assistant.html - probably different URLs for different locales).

**Comment by gwarser** [comment]
Please try:

    @@||127.0.0.1^*/intel/$image,xhr,domain=www.intel.com

**Comment by Jap2-0** [comment]
That does fix the issue.

It appears that all of the requests are xhr along the path `http://127.0.0.1:28385/intel/v1.0/*`.  It also attempts to connect over a websocket to `ws://127.0.0.1:28390/` which is still blocked, but that does not appear to impact functionality in any way, so I'm not sure what the point of the websocket is.

**Comment by krystian3w** [comment]
Images aren't needed to use test, page most based on xhr requests to load info out of scope for browsers "API".

**Comment by krystian3w** [comment]
Also Polish test is broken, so may need generate list of "TLD" in Intel hands if `intel.*` are bad (match 1500+ combinations):

(https://www.intel.pl/content/www/pl/pl/support/intel-driver-support-assistant.html)

**Comment by gwarser** [comment]
`@@||127.0.0.1^*/intel/$xhr,domain=www.intel.*` then?
