### ISSUE TITLE
Add router.asus.com to lan-block.txt

### ISSUE THREAD

**Issue by WolfgangWeber** [gwarser/filter-lists#2]
router.asus.com is another router domain that might be added to the list:

> $ dig router.asus.com
>
>; <<>> DiG 9.11.18-RedHat-9.11.18-1.fc32 <<>> router.asus.com
>;; global options: +cmd
>;; Got answer:
>;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 48126
>;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1
>
>;; OPT PSEUDOSECTION:
>; EDNS: version: 0, flags:; udp: 1280
>;; QUESTION SECTION:
>;router.asus.com.		IN	A
>
>;; ANSWER SECTION:
>router.asus.com.	0	IN	A	192.168.1.1
>
>;; Query time: 0 msec
>;; SERVER: 192.168.1.1#53(192.168.1.1)
>;; WHEN: So Mai 31 22:17:39 CEST 2020
>;; MSG SIZE  rcvd: 60

Thanks for your work!

**Comment by gwarser** [comment]
Thanks!
