### ISSUE TITLE
Add home.arpa. to lan-block.

### ISSUE THREAD

**Issue by AnAccountForReportingBugs** [gwarser/filter-lists#22]
The LAN block list does not contain an entry for home.arpa. This domain name suffix was reserved in 2018 for special use by the IETF in RFC 8375.

**Comment by gwarser** [comment]
All these [`.in-addr.arpa`](https://en.wikipedia.org/wiki/Special-use_domain_name) pointing to local IP will need to be blocked too??

**Comment by gwarser** [comment]
`.arpa` issue: https://github.com/gwarser/filter-lists/issues/23

**Comment by AnAccountForReportingBugs** [comment]
Thank you for your swift attention. Keep up the good work!
