### ISSUE TITLE
plex.direct

### ISSUE THREAD

**Issue by DandelionSprout** [gwarser/filter-lists#26]
I've received word in https://github.com/AdguardTeam/AdGuardHome/issues/1446#issuecomment-958005231 that `plex.direct` is a somewhat major "URL → LAN-IP" redirector, like what all the router URLs such as `router.asus.com` and `routerlogin.net` are.

Therefore I at least presume `||plex.direct^$third-party,domain=~localhost|~127.0.0.1|~[::1]|~0.0.0.0|~[::]|~local` could be added to *Block Access to LAN*.

**Comment by timkgh** [comment]
https://support.plex.tv/articles/206225077-how-to-use-secure-server-connections/  talks about `plex.direct` and DNS rebinding.

**Comment by gwarser** [comment]
Will it need to be allowed on `app.plex.tv`?

**Comment by timkgh** [comment]
Yes, there are requests to plex.direct from app.plex.tv, the URL look something like:
`https://192-168-1-20.<uuid>.plex.direct:32400/...`
where `192-168-1-20.<uuid>.plex.direct` resolves to `192.168.1.20`
