### ISSUE TITLE
Rename "Block Access to LAN" to avoid fears of blocking local servers or file addresses

### ISSUE THREAD

**Issue by DandelionSprout** [gwarser/filter-lists#27]
So here's the background story: I waited perhaps a full year before enabling the *Block Access to LAN* list on my PC and phone, because the short title and slightly too short description made me worried it'd block e.g. `http://192.168.1.163/` or `C:\Users\example\OneDrive\Documents`, as it was unclear from the metadata alone that it only prevents *public* sites from accessing LAN content.

Therefore I propose the list be renamed `! Title: Block Outsider Intrusion into LAN`, and the description be changed into something approximate to `! Description: Prevents public internet sites from digging into your local LAN files, and can also help mitigate DNS rebind attacks.`

**Comment by gwarser** [comment]
@DandelionSprout what you think?

>Rename it to Block Third-party Access to LAN ? better than "Outsider Intrusion" imo.

https://github.com/gorhill/uBlock/pull/3861#issuecomment-970397827

**Comment by DandelionSprout** [comment]
That works too.
