### ISSUE TITLE
Add ipv6 local network filters

### ISSUE THREAD

**Issue by gwarser** [gwarser/filter-lists#3]
https://github.com/uBlockOrigin/uBlock-issues/issues/1070

What is still missing in my list is ipv6 handling https://en.wikipedia.org/wiki/Private_network#Private_IPv6_addresses. No one will scan these addresses from a to z, but some software can still be listening on one.

Calculator https://www.vultr.com/resources/subnet-calculator-ipv6/

- `fc00::/7` ranges from `fc00:0000:0000:0000:0000:0000:0000:0000` to `fdff:ffff:ffff:ffff:ffff:ffff:ffff:ffff`

	`||[fc*]^`
	`||[fd*]^`

- `fd00::/8` should be included in above -  `fd00:0000:0000:0000:0000:0000:0000:0000` to `fdff:ffff:ffff:ffff:ffff:ffff:ffff:ffff`
- legacy "site-local" `fec0::/10` - `fec0:0000:0000:0000:0000:0000:0000:0000` to `feff:ffff:ffff:ffff:ffff:ffff:ffff:ffff`

	`||[fec*]^`
	`||[fed*]^`
	`||[fee*]^`
	`||[fef*]^`

I'm not sure my filters above are actually valid or if these addresses can be so easily matched by simple text comparison with wildcard. Is `[` and `]` invalid in normal domain name? Someone with better knowledge about ipv6 address formatting will need to say. It may be good based on this: https://en.wikipedia.org/wiki/IPv6_address#Representation

**Comment by gwarser** [comment]
Better calc http://www.gestioip.net/cgi-bin/subnet_calculator.cgi

**Comment by gwarser** [comment]
Hmmm, does it have the same issue as in https://github.com/gwarser/filter-lists/issues/6#issuecomment-637020333 ?

`fc*` can be `fc00:...`, `fc0:...`, `fc:...`.

**Comment by curiosityseeker** [comment]
I'm not an expert in these things at all. Just mentioning that the [Behave](https://github.com/mindedsecurity/behave) add-on uses [these](https://github.com/mindedsecurity/behave/blob/master/background.js#L85) rules. No idea if that's helpful for you ...

**Comment by gwarser** [comment]
Only this part is about ipv6 `(^[fF][cCdD])` - this matches `fc` or `fd` and:

>`[fc*` can be `[fc00:...`, `[fc0:...`, `[fc:...`.

**Comment by gwarser** [comment]
/^https?://\[f(?:[cd][0-9a-f]{2}|e[c-f][0-9a-f]):[0-9a-f:]+\][:/]/$third-party,~websocket
    /^wss?://\[f(?:[cd][0-9a-f]{2}|e[c-f][0-9a-f]):[0-9a-f:]+\][:/]/$third-party,websocket

https://regex101.com/r/O0tAKl/1

**Comment by gwarser** [comment]
For not tokenizable regexes it may be good idea to compile only one regular expression.

    /^(?:http|ws)s?://\[f(?:[cd][0-9a-f]|e[c-f])[0-9a-f]:[0-9a-f:]+\][:/]/$third-party

https://regex101.com/r/O0tAKl/2
