### ISSUE TITLE
A question about the LAN filter

### ISSUE THREAD

**Issue by furt555nv** [gwarser/filter-lists#30]
Sorry for this spam thread. I'm not a developer but I want to learn something.

Is your LAN filter for standard web browsing or a DNS filter? I don't use DNS on my devices

`https://github.com/gwarser/filter-lists/blob/master/lan-block.txt`

**Comment by gwarser** [comment]
It's meant to be used in browser extensions (ad blockers). It uses filter format compatible with those (mainly uBlock Origin).

I don't even think these connections it attempt to block even reach DNS servers - they are local IP addresses or domains hardcoded in local network devices like modems or routers.

**Comment by furt555nv** [comment]
I think I got it. I think this filter is suitable for use with the AdGuard extension. 
Thanks.
