### ISSUE TITLE
Too many domains allowed in the exception for Intel in *Block Outsider Intrusion into LAN*

### ISSUE THREAD

**Issue by dungsaga** [gwarser/filter-lists#31]
Ticket #19 introduced an exception for Intel Drivers and Support Assistant
```
@@||127.0.0.1^*/intel/$xhr,domain=www.intel.*
```
This change allowed too many domains and it could be used in attacks (such as from www.intel.any.domain.com).

I proposed that we restrict this exception to the domains used by Intel.
Here is the list of domains I collected from the page Intel Drivers and Support Assistant (https://www.intel.com/content/www/us/en/support/intel-driver-support-assistant.html):
```
www.intel.ca
www.intel.cn
www.intel.co
www.intel.com
www.intel.de
www.intel.es
www.intel.fr
www.intel.ie
www.intel.in
www.intel.it
www.intel.la
www.intel.pl
www.intel.ru
www.intel.sg
www.intel.vn
www.thailand.intel.com
```
![image](https://user-images.githubusercontent.com/5884951/157568648-4afe4ced-90c1-4899-8920-aca8bd199798.png)

**Comment by dungsaga** [comment]
oops, it looks like the list *Block Outsider Intrusion into LAN* was maintains in the repository uBlockOrigin/uAssets, so I cloned this issue to https://github.com/uBlockOrigin/uAssets/issues/12139

**Comment by gwarser** [comment]
https://github.com/uBlockOrigin/uAssets/commit/65c98c7429673ca8ad1433fc2fe7c1cc607dbd4c
