### ISSUE TITLE
Is unblocking access in local network between various addresses worth supporting?

### ISSUE THREAD

**Issue by gwarser** [gwarser/filter-lists#8]
||127.0.0.1^$third-party,domain=~localhost|~[::1]|~local|???

https://github.com/uBlockOrigin/uBlock-issues/issues/1249#issuecomment-693726433

**Comment by PinkDev1** [comment]
Probably not.
Personally: on local websites I trust, I simply prefer to disable uBlockOrigin (if it even conflicts with anything)
If I couldn't trust said website to _behave_, I wouldn't be hosting it on my local network

**Comment by gwarser** [comment]
https://www.reddit.com/r/uBlockOrigin/comments/jqd9mp/local_and_remote_filters/

**Comment by QuantumWarpCode** [comment]
I think that this is worth adding to the list as I have two test servers set up on different machines on my local network. I like to test if any of the default lists interfere with my content.

**Comment by gwarser** [comment]
What type of addresses are you using? Any specific IP ranges? `.local` TLD?

I can include only limited set of addresses in `domain` option. Definitely not IP ranges.

    ...$third-party,domain=~localhost|~[::1]|~127.0.0.1|~0.0.0.0|~[::]|~???

**Comment by QuantumWarpCode** [comment]
Localhost is connecting to 10.0.0.* addresses to download images, style-sheets, and scripts. My guess would be that anyone else doing the same thing just needs localhost and it's various aliases whitelisted. Hopefully that is a small enough set of exclusions to prevent any significant performance drop.
